#!/usr/bin/env python3

from collections import defaultdict
import json

from tabulate import tabulate
from icecream import ic

from fuzzy_index import FuzzyIndex
from utils import split_list_evenly, split_dict_evenly


with open("../typesense_queries.txt", "r") as f:
    index = defaultdict(int)
    for line in f.readlines():
        d = json.loads(line)
        encoded = FuzzyIndex.encode_string(d["artist"])
        if encoded:
            index[encoded[0]] += 1

print("# generated by shard_generator.py. DO NOT EDIT.")
print("shard_histogram = {")
for k in sorted(index, key=lambda x: index[x], reverse=True):
    print(f'    "{k}": {index[k]},')
print("}")
